update readme documentation
incandenza-11/blockout2024 pull request #12
Opened 2024-05-19 21:40 UTC by loosiegoosey

2024-05-20 10:49 UTC, incandenza-11 commented on README.md
@loosiegoosey You need to rebase (synch) your branch with main because it seems it doesn't have the last changes :)

2024-05-20 10:54 UTC, incandenza-11 commented on README.md
> +   cd BlockOut2024
hence, `cd blockout2024`

2024-05-20 10:57 UTC, incandenza-11 commented on README.md
> +- `resources/example.jpeg`: Example output image for the `README.md`.
I'd remove all the files that are not needed to run the script, as the inner structure is eager to change when adding new features, this can be difficult to maintain after a while. So I'd suggest keeping:

- `main.py`: The entry point to execute the blocking functionality.
- `requirements.txt`: Lists the Python dependencies required by the script.
- `resources/usernames/`: The directory where all the usernames to be blocked are located; separated by social media type.

2024-05-20 11:00 UTC, incandenza-11 commented on README.md
> +
Same as in the file structure case, as the `requirements.txt` file is going to change quite often (when adding new dependencies and when upgrading their versions), it's going to get harder to maintain it here. So, as it is duplicated information, I'd just either mention the `requirements.txt` file here instead of listing its contents or maybe just skip this Dependencies section entirely.

2024-05-20 11:02 UTC, incandenza-11 commented on README.md
Great job, thanks a lot! 🚀 I've requested some changes, I'll approve and close the PR once that's solved :)

2024-05-20 11:03 UTC, incandenza-11 requested changes

2024-05-20 11:03 UTC, incandenza-11 commented on README.md
> +   git clone https://github.com/your-username/BlockOut2024.git
`your-username` is not correct here, as it's cloning the repository located at my user's GitHub, so the exact URL should be: https://github.com/incandenza-11/blockout2024

2024-05-20 11:03 UTC, incandenza-11 commented on README.md
> +   cd BlockOut2024
hence here, cd blockout2024

2024-05-20 11:03 UTC, incandenza-11 commented on README.md
> +- `pillow==10.3.0`
Same as in the file structure case, as the `requirements.txt` file is going to change quite often (when adding new dependencies and when upgrading their versions), it's going to get harder to maintain it here. So, as it is duplicated information, I'd just either mention the `requirements.txt` file here instead of listing its contents or maybe just skip this Dependencies section entirely.

2024-05-20 11:03 UTC, incandenza-11 commented on README.md
> +- `resources/example.jpeg`: Example output image for the `README.md`.
I'd remove all the files that are not needed to run the script, as the inner structure is eager to change when adding new features, this can be difficult to maintain after a while. So I'd suggest keeping:

- `main.py`: The entry point to execute the blocking functionality.
- `requirements.txt`: Lists the Python dependencies required by the script.
- `resources/usernames/`: The directory where all the usernames to be blocked are located; separated by social media type.

2024-05-20 15:05 UTC, loosiegoosey commented on README.md
> +- `resources/example.jpeg`: Example output image for the `README.md`.
removed files unnecessary to run the script

2024-05-20 15:07 UTC, loosiegoosey commented on README.md
> +- `pillow==10.3.0`
removed dependencies section

2024-05-20 15:09 UTC, loosiegoosey commented on README.md
> +   git clone https://github.com/your-username/BlockOut2024.git
revised the git URL to include new owner name and made the repo lowercase

2024-05-20 15:10 UTC, loosiegoosey commented on README.md
> +   cd BlockOut2024
made the repo folder name lowercase

2024-05-22 01:58 UTC, closed without merging

2024-05-22 07:53 UTC, molinto commented on instagram_usernames.txt
> +aoc
https://x.com/RepAOC/status/1771238247449899285?lang=en